[simulation]
# max_displacement = 3.0
leaking_edges = true
calculate_gradients = true
run_mechanical_interactions = false

[neuroscience]
neurite_min_length = 1.0
neurite_max_length = 2.0

[visualization]
export = false
live = false
export_interval = 16

    [[visualize_sim_object]]
    name = "MyCell"
    additional_data_members = [ "cell_type_" ]

    [[visualize_sim_object]]
    name = "MyNeurite"
    additional_data_members = [ "subtype_" ]

    # [[visualize_diffusion]]
    # name = "on_diffusion"

    # [[visualize_diffusion]]
    # name = "off_diffusion"

    # [[visualize_diffusion]]
    # name = "off_substance_RGC_guide"
